// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"microdule-layout/pkg"
)

// Injectors from wire.go:

func InitService() (*pkg.App, error) {
	global, err := pkg.InitGlobal()
	if err != nil {
		return nil, err
	}
	redis := pkg.InitRedis(global)
	db := pkg.InitOrm(global)
	etcd := pkg.InitEtcd(global)
	gin := pkg.InitRest(global)
	app := NewService(global, redis, db, etcd, gin)
	return app, nil
}
